electronic_certification/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('myapp.urls')),
]

myapp/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'myapp'
urlpatterns = [
                  # http://127.0.0.1:8000/
                  url(r'^$', views.login, name='login'),
                  # http://127.0.0.1:8000/index/
                  url(r'^index$', views.index, name='index'),

                  # http://127.0.0.1:8000/person/
                  url(r'^person$', views.person, name='person'),

                  # http://127.0.0.1:8000/upload/
                  url(r'^upload$', views.upload, name='upload'),
                  # http://127.0.0.1:8000/upload_sfz/
                  url(r'^upload_sfz$', views.upload_sfz, name='upload_sfz'),
                  # http://127.0.0.1:8000/upload_yyzz/
                  url(r'^upload_yyzz$', views.upload_yyzz, name='upload_yyzz'),

                  # http://127.0.0.1:8000/see/
                  url(r'^see$', views.see, name='see'),
                  # http://127.0.0.1:8000/see_sfz/
                  url(r'^see_sfz$', views.see_sfz, name='see_sfz'),
                  # http://127.0.0.1:8000/see_yyzz/
                  url(r'^see_yyzz$', views.see_yyzz, name='see_yyzz'),
                  # 用户
                  url(r'^login$', views.login, name='login'),
                  url(r'^login_check$', views.login_check, name='login_check'),
                  url(r'^logout$', views.logout, name='logout'),

                  # 注册
                  url(r'^register/$', views.register, name='register'),
                  url(r'^register_handle/$', views.register_handle, name='register_handle'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh_CN">
<head>
    <meta charset="utf-8">
    <title>{% block title %} 电子证照管理系统{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--必备的Css-->
    <link href="{% static 'assets/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/theme.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/alertify.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/opp-app.css' %}" rel="stylesheet">


    {% block css %}

    {% endblock %}

    {% block js %}

    {% endblock %}
</head>
<body>
<div id="wrap">
    <!-- navbar-->
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                {% include 'navbar.html' %}
            </div>
        </div>
    </div>
    <!--/ navbar-->
    <div class="container-fluid">
        <!-- Side menu -->
        <div class="sidebar-nav nav-collapse collapse">
            <div class="user_side clearfix">
                <img src="{% static 'assets/img/examinee.jpg' %}" alt="Odinn god of Thunder">
                <h5 id="currentuser"></h5>
                <a href="{% url 'myapp:person' %}"><i class="icon-cog"></i> {{ request.session.username }}的个人中心</a>
            </div>
            {% include 'menu.html' %}
        </div>
    </div>
    <!-- /Side menu -->
    {% block content %}

    {% endblock %}
</div>

</body>
<script type="text/javascript" src="{% static 'assets/js/angular.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/jquery.min.js' %}"></script>
{#<script type="text/javascript" src="{% static 'assets/js/jquery.cookie.js' %}"></script>#}
<script type="text/javascript" src="{% static 'assets/js/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/raphael-min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/bootstrap.js' %}"></script>
<script type="text/javascript" src='{% static 'assets/js/sparkline.js' %}'></script>
<script type="text/javascript" src='{% static 'assets/js/morris.min.js' %}'></script>
<script type="text/javascript" src="{% static 'assets/js/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/jquery.masonry.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/jquery.imagesloaded.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/jquery.facybox.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/jquery.alertify.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/jquery.knob.js' %}"></script>
<script type='text/javascript' src='{% static 'assets/js/fullcalendar.min.js' %}'></script>
<script type='text/javascript' src='{% static 'assets/js/jquery.gritter.min.js' %}'></script>
<script type="text/javascript" src="{% static 'assets/js/realm.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/layer.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/opp-app.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/opp-setting.js' %}"></script>

<script type="text/javascript" src="{% static 'assets/js/select2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/bootstrap-colorpicker.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/bootstrap-datepicker.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/bootstrap-timepicker.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/opp-scorepersonal.js' %}"></script>
{% block downjs %}

{% endblock %}
</html>

templates/menu.html
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle b_F79999" href="{% url 'myapp:index' %}"><i class="icon-dashboard"></i>
                <span>首页主界面</span></a>
        </div>
    </div>
    <div class="accordion-group">
        <a class="accordion-toggle b_F6F1A2" href="{% url 'myapp:person' %}"><i class="icon-user"></i>
            <span>个人信息管理</span></a>
    </div>
    <div class="accordion-group">
        <a class="accordion-toggle b_F6F1A2" href="{% url 'myapp:upload' %}"><i class="icon-upload"></i>
            <span>上传电子证照信息</span></a>
    </div>
    <div class="accordion-group">
        <a class="accordion-toggle b_F6F1A2" href="{% url 'myapp:see' %}"><i class="icon-heart"></i>
            <span>查看电子证照信息</span></a>
    </div>
    <div class="accordion-group">
        <a class="accordion-toggle b_F6F1A2" href="{% url 'myapp:upload_sfz' %}"><i class="icon-upload"></i>
            <span>上传身份证信息</span></a>
    </div>

    <div class="accordion-group">
        <a class="accordion-toggle b_F6F1A2" href="{% url 'myapp:see_sfz' %}"><i class="icon-heart"></i>
            <span>查看身份证信息</span></a>
    </div>
    <div class="accordion-group">
        <a class="accordion-toggle b_F6F1A2" href="{% url 'myapp:upload_yyzz' %}"><i class="icon-upload"></i>
            <span>上传营业执照信息</span></a>
    </div>

    <div class="accordion-group">
        <a class="accordion-toggle b_F6F1A2" href="{% url 'myapp:see_yyzz' %}"><i class="icon-heart"></i>
            <span>查看营业执照信息</span></a>
    </div>
</div>

templates/navbar.html
{% load staticfiles %}
<!-- navbar-->
<div class="logo">
    <img src="{% static 'assets/img/logo.png' %}" alt="Realm Admin Template">
</div>
<a class="btn btn-navbar visible-phone" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
</a>
<a class="btn btn-navbar slide_menu_left visible-tablet">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
</a>

<div class="top-menu visible-desktop">
    <ul class="pull-left">
        <li><a href="javascript:;"><i class="icon-globe"></i>  电子证照管理系统</a></li>
    </ul>
    <ul class="pull-right">
        <li><a href="{% url 'myapp:logout' %}"><i class="icon-off"></i> 退出</a></li>
    </ul>
</div>

<div class="top-menu visible-phone visible-tablet">
    <ul class="pull-right">
        <li><a href="login.html"><i class="icon-off"></i> </a></li>
    </ul>
</div>
<!--/ navbar-->